language: php
php:
  #- 5.4
  #- 5.5
  #- 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1
os: linux
before_script:
  - travis_retry composer instal
  - php artisan key:generate   
  - php artisan jwt:secret
script:
  - vendor/bin/phpunit
