#matrix:
#include:
language: php

php:
  - 7.3
  - 7.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit
    
#-language: node_js
    
 # node_js:
 # - "stable"
 #cache:
 # directories:
 # - node_modules
 # script:
 # - npm test
 # - npm run build


#Initial echo test :Travis for nodejs
#language: node_js
#node_js:
 # - "node"
  #- "6"
  #- "4"

#attemtp to resolve Travis Issue:
#   make: *** No rule to make target 'test'.  Stop.
#   The command "make test" exited with 2.
#script:
  #- echo "Hello World"
